// Elementos da página
const form = document.querySelector("form");
const amount = document.getElementById("amount");
const initial = document.getElementById("from");
const final = document.getElementById("to");
const checkBox = document.getElementById("checkbox");
const contentForm = document.querySelector(".content-form");
const formResults = document.querySelector(".form-results");
const results = document.getElementsByClassName("results");
